import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { AIInsight } from "@/components/ai/ai-insight";

export default async function ClientPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params; const s=await createClient(); const {data:{claims}}=await s.auth.getClaims(); if(!claims?.sub) redirect("/auth");
 const {data:m}=await s.from("workspace_members").select("workspace_id").eq("user_id",claims.sub).limit(1).maybeSingle(); if(!m) redirect("/onboarding");
 const {data:client}=await s.from("clients").select("id,name,company_name,email,phone,status,notes,created_at").eq("id",id).eq("workspace_id",m.workspace_id).maybeSingle(); if(!client) redirect("/app/clients");
 const {data:actions}=await s.from("actions").select("id,title,reason,priority,status,due_at").eq("client_id",id).eq("workspace_id",m.workspace_id).order("due_at",{ascending:true});
 const {data:activities}=await s.from("activities").select("id,type,title,description,created_at").eq("client_id",id).eq("workspace_id",m.workspace_id).order("created_at",{ascending:false}).limit(30);
 return <main className="px-6 py-10"><div className="mx-auto max-w-6xl"><a href="/app/clients" className="text-sm text-slate-500">← Clients</a><div className="mt-5 rounded-3xl border bg-white p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-3xl font-semibold text-[#0b1736]">{client.name}</h1><p className="mt-1 text-slate-500">{client.company_name||client.email||"No contact details"}</p></div><a href={"/app/actions/new?client="+client.id} className="rounded-xl bg-[#0b1736] px-4 py-3 text-sm font-semibold text-white">+ Create action</a></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Status</p><p className="mt-1 font-semibold">{client.status}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Open actions</p><p className="mt-1 font-semibold">{actions?.filter(a=>a.status!=="completed").length||0}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Contact</p><p className="mt-1 font-semibold">{client.email||"—"}</p></div></div></div><div className="mt-6"><AIInsight clientId={client.id} /></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-semibold">Next actions</h2><div className="mt-4 space-y-3">{actions?.length?actions.map(a=><div key={a.id} className="rounded-2xl border p-4"><div className="flex justify-between gap-3"><p className="font-semibold">{a.title}</p><span className="text-xs uppercase text-blue-600">{a.priority}</span></div><p className="mt-1 text-sm text-slate-500">{a.reason||"No reason added"} · {a.status}</p></div>):<p className="py-6 text-sm text-slate-500">No actions yet.</p>}</div></section><section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-semibold">Activity</h2><div className="mt-4 space-y-4">{activities?.length?activities.map(e=><div key={e.id} className="border-l-2 pl-4"><p className="font-medium">{e.title}</p><p className="text-sm text-slate-500">{e.description||e.type}</p><p className="mt-1 text-xs text-slate-400">{new Date(e.created_at).toLocaleString()}</p></div>):<p className="py-6 text-sm text-slate-500">No activity yet.</p>}</div></section></div></div></main>