import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export default async function InvoiceDetail({params}:{params:Promise<{id:string}>}){
 const {id}=await params; const s=await createClient(); const { data: claimsData } = await s.auth.getClaims(); const claims = claimsData?.claims; if(!claims?.sub)redirect("/auth");
 const {data:m}=await s.from("workspace_members").select("workspace_id").eq("user_id",claims.sub).limit(1).maybeSingle(); if(!m)redirect("/onboarding");
 const {data:i}=await s.from("invoices").select("id,invoice_number,amount,currency,issue_date,due_date,status,description,notes,client_id,clients(name,email),payments(id,amount,payment_date,method,notes)").eq("id",id).eq("workspace_id",m.workspace_id).maybeSingle(); if(!i)redirect("/app/payments");
 const paid=(i.payments||[]).reduce((x:number,p:any)=>x+Number(p.amount),0); const remaining=Math.max(0,Number(i.amount)-paid);
 return <main className="px-6 py-10"><div className="mx-auto max-w-4xl"><a href="/app/payments" className="text-sm text-slate-500">← Payments</a><div className="mt-5 rounded-3xl border bg-white p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-blue-600">Invoice</p><h1 className="mt-2 text-3xl font-semibold text-[#0b1736]">{i.invoice_number||"Invoice"}</h1><p className="mt-2 text-slate-500"><a href={"/app/clients/"+i.client_id} className="text-blue-600">{i.clients?.[0]?.name}</a>{i.clients?.[0]?.email?" · "+i.clients?.[0]?.email:""}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold uppercase">{i.status}</span></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Total</p><p className="mt-1 text-xl font-semibold">{Number(i.amount).toFixed(2)} {i.currency}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Paid</p><p className="mt-1 text-xl font-semibold">{paid.toFixed(2)} {i.currency}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Remaining</p><p className="mt-1 text-xl font-semibold">{remaining.toFixed(2)} {i.currency}</p></div></div><div className="mt-7 grid gap-4 sm:grid-cols-2"><div><p className="text-xs text-slate-500">Issued</p><p className="mt-1">{i.issue_date}</p></div><div><p className="text-xs text-slate-500">Due</p><p className="mt-1">{i.due_date}</p></div></div>{i.description&&<p className="mt-6 text-sm text-slate-600">{i.description}</p>}<div className="mt-8 flex flex-wrap gap-3"><a href={"/app/payments/record?invoice="+i.id} className="rounded-xl bg-[#0b1736] px-5 py-3 text-sm font-semibold text-white">Record payment</a><a href={"/app/actions/new?client="+i.client_id} className="rounded-xl border px-5 py-3 text-sm font-semibold">Create next action</a></div></div><section className="mt-6 rounded-3xl border bg-white p-7"><h2 className="text-xl font-semibold text-[#0b1736]">Payment timeline</h2><div className="mt-5 space-y-5"><div className="border-l-2 border-slate-200 pl-5"><p className="font-medium">Invoice created</p><p className="text-sm text-slate-500">{i.issue_date} · {Number(i.amount).toFixed(2)} {i.currency}</p></div>{i.payments?.map((p:any)=><div key={p.id} className="border-l-2 border-slate-200 pl-5"><p className="font-medium">Payment received</p><p className="text-sm text-slate-500">{p.payment_date} · {Number(p.amount).toFixed(2)} {i.currency} · {p.method}</p></div>)}<div className="border-l-2 border-slate-200 pl-5"><p className="font-medium">{i.status==="paid"?"Paid":"Payment status"}</p><p className="text-sm text-slate-500">{remaining.toFixed(2)} {i.currency} remaining</p></div></div></section></div></main>
}
