import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export default async function PaymentsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; page?: string }> }) {
 const params=await searchParams; const q=(params.q||"").trim(); const status=params.status||"all"; const page=Math.max(1,Number(params.page)||1); const pageSize=25;
 const s=await createClient(); const { data: claimsData } = await s.auth.getClaims(); const claims = claimsData?.claims; if(!claims?.sub)redirect("/auth");
 const {data:m}=await s.from("workspace_members").select("workspace_id").eq("user_id",claims.sub).limit(1).maybeSingle(); if(!m)redirect("/onboarding");
 await s.rpc("refresh_overdue_invoices");
 let query=s.from("invoices").select("id,invoice_number,amount,currency,due_date,status,clients(name),payments(amount)",{count:"exact"}).eq("workspace_id",m.workspace_id).order("due_date",{ascending:true});
 if(q) query=query.or(`invoice_number.ilike.%${q}%`);
 if(status!=="all") query=query.eq("status",status);
 const {data:invoices,count}=await query.range((page-1)*pageSize,page*pageSize-1);
 const rows=(invoices||[]).map((i:any)=>{const paid=(i.payments||[]).reduce((x:number,p:any)=>x+Number(p.amount),0);return {...i,paid,remaining:Math.max(0,Number(i.amount)-paid)}});
 const hasNext=(count||0)>page*pageSize; const qs=(p:number)=>`?q=${encodeURIComponent(q)}&status=${encodeURIComponent(status)}&page=${p}`;
 const {data:summaryInvoices}=await s.from("invoices").select("amount,status,payments(amount)").eq("workspace_id",m.workspace_id); const summary=(summaryInvoices||[]).reduce((acc:any,i:any)=>{const paid=(i.payments||[]).reduce((x:number,p:any)=>x+Number(p.amount),0);const remaining=Math.max(0,Number(i.amount)-paid);acc.outstanding+=remaining;acc.paid+=paid;if(i.status==="overdue")acc.overdue+=remaining;return acc;},{outstanding:0,overdue:0,paid:0});
 return <main className="px-6 py-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-blue-600">Payments</p><h1 className="mt-2 text-4xl font-semibold text-[#0b1736]">Track what’s paid, pending, and overdue.</h1></div><div className="flex gap-2"><a href="/app/payments/new" className="rounded-xl bg-[#0b1736] px-4 py-3 text-sm font-semibold text-white">+ Invoice</a><a href="/app/payments/record" className="rounded-xl border bg-white px-4 py-3 text-sm font-semibold">Record payment</a></div></div>
 <div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Outstanding</p><p className="mt-1 text-2xl font-semibold">{summary.outstanding.toFixed(2)}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Overdue</p><p className="mt-1 text-2xl font-semibold">{summary.overdue.toFixed(2)}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">Paid</p><p className="mt-1 text-2xl font-semibold">{summary.paid.toFixed(2)}</p></div></div>
 <form className="mt-8 flex flex-col gap-3 sm:flex-row"><input name="q" defaultValue={q} placeholder="Search invoice number..." className="flex-1 rounded-xl border bg-white px-4 py-3 text-sm"/><select name="status" defaultValue={status} className="rounded-xl border bg-white px-4 py-3 text-sm"><option value="all">All statuses</option><option value="draft">Draft</option><option value="sent">Sent</option><option value="pending">Pending</option><option value="partially_paid">Partially paid</option><option value="paid">Paid</option><option value="overdue">Overdue</option></select><button className="rounded-xl border bg-white px-5 py-3 text-sm font-semibold">Filter</button></form>
 <div className="mt-6 overflow-hidden rounded-3xl border bg-white"><div className="divide-y">{rows.length?rows.map((i:any)=><div key={i.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><a href={"/app/payments/"+i.id} className="font-semibold text-[#0b1736] hover:text-blue-600">{i.clients?.name||"Client"}</a><p className="text-sm text-slate-500">{i.invoice_number||"Invoice"} · {i.amount} {i.currency} · due {i.due_date}</p><p className="mt-1 text-xs text-slate-400">Paid {i.paid.toFixed(2)} · Remaining {i.remaining.toFixed(2)}</p></div><span className={"w-fit rounded-full px-3 py-1 text-xs font-bold uppercase "+(i.status==="overdue"?"bg-red-50 text-red-700":i.status==="paid"?"bg-green-50 text-green-700":"bg-slate-100 text-slate-600")}>{i.status}</span></div>):<div className="p-12 text-center text-sm text-slate-500">{q||status!=="all"?"No matching invoices. Try another filter.":"No invoices yet."}</div>}</div></div>
 {(page>1||hasNext)&&<div className="mt-5 flex items-center justify-between"><span className="text-sm text-slate-500">Page {page}{count!==null&&count!==undefined?` · ${count} total`:""}</span><div className="flex gap-2">{page>1&&<a href={qs(page-1)} className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Previous</a>}{hasNext&&<a href={qs(page+1)} className="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Next</a>}</div></div>}
 </div></main>;
}