import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

function isTodayOrPast(value:string|null){if(!value)return false;return new Date(value)<=new Date();}
function groupStatus(a:any){if(a.status==="completed")return "completed";if(a.status==="waiting")return "waiting";if(isTodayOrPast(a.due_at))return "attention";return "upcoming";}

export default async function TodayPage(){
 const supabase=await createClient(); const {data:{claims}}=await supabase.auth.getClaims(); if(!claims?.sub)redirect("/auth");
 const {data:m}=await supabase.from("workspace_members").select("workspace_id").eq("user_id",claims.sub).limit(1).maybeSingle(); if(!m)redirect("/onboarding");
 const {data:actions}=await supabase.from("actions").select("id,title,reason,priority,status,due_at,completed_at,clients(name)").eq("workspace_id",m.workspace_id).order("due_at",{ascending:true}).limit(100);
 const groups={attention:[] as any[],waiting:[] as any[],completed:[] as any[],upcoming:[] as any[]}; (actions||[]).forEach(a=>groups[groupStatus(a)].push(a));
 const Card=({a}:{a:any})=><div className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-[#0b1736]">{a.title}</p><p className="mt-1 text-sm text-slate-500">{a.clients?.name||"Client"}</p>{a.reason&&<p className="mt-2 text-sm text-slate-600">{a.reason}</p>}</div><span className={"rounded-full px-2.5 py-1 text-[11px] font-bold uppercase "+(a.priority==="high"?"bg-red-50 text-red-700":a.priority==="medium"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-600")}>{a.priority}</span></div><div className="mt-4 flex items-center justify-between text-xs text-slate-500"><span>{a.due_at?"Due "+new Date(a.due_at).toLocaleString():"No due date"}</span><a href={"/app/actions/"+a.id} className="font-semibold text-blue-600">Review →</a></div></div>;
 return <main className="px-6 py-10"><div className="mx-auto max-w-7xl"><div><p className="text-sm font-semibold text-blue-600">Today</p><h1 className="mt-2 text-4xl font-semibold text-[#0b1736]">Here’s what needs your attention.</h1><p className="mt-2 text-slate-500">Actionora turns pending client situations into clear next actions.</p></div><div className="mt-8 grid gap-3 sm:grid-cols-4"><div className="rounded-2xl border bg-white p-4"><p className="text-sm text-slate-500">Need action</p><p className="mt-1 text-3xl font-semibold">{groups.attention.length}</p></div><div className="rounded-2xl border bg-white p-4"><p className="text-sm text-slate-500">Waiting</p><p className="mt-1 text-3xl font-semibold">{groups.waiting.length}</p></div><div className="rounded-2xl border bg-white p-4"><p className="text-sm text-slate-500">Upcoming</p><p className="mt-1 text-3xl font-semibold">{groups.upcoming.length}</p></div><div className="rounded-2xl border bg-white p-4"><p className="text-sm text-slate-500">Completed</p><p className="mt-1 text-3xl font-semibold">{groups.completed.length}</p></div></div><section className="mt-8"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold text-[#0b1736]">Need action now</h2><a href="/app/actions/new" className="rounded-xl bg-[#0b1736] px-4 py-2.5 text-sm font-semibold text-white">+ Action</a></div><div className="mt-4 grid gap-3">{groups.attention.length?groups.attention.map(a=><Card key={a.id} a={a}/>):<div className="rounded-3xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">You’re clear for now. No action is due.</div>}</div></section><div className="mt-8 grid gap-8 lg:grid-cols-2"><section><h2 className="text-xl font-semibold text-[#0b1736]">Waiting</h2><div className="mt-4 space-y-3">{groups.waiting.slice(0,5).map(a=><Card key={a.id} a={a}/>)}</div></section><section><h2 className="text-xl font-semibold text-[#0b1736]">Upcoming</h2><div className="mt-4 space-y-3">{groups.upcoming.slice(0,5).map(a=><Card key={a.id} a={a}/>)}</div></section></div></div></main>;
}