import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

function dueNow(v:string|null){return !!v&&new Date(v)<=new Date();}
export default async function TodayPage(){
 const s=await createClient();const {data:{claims}}=await s.auth.getClaims();if(!claims?.sub)redirect("/auth");
 const {data:m}=await s.from("workspace_members").select("workspace_id").eq("user_id",claims.sub).limit(1).maybeSingle();if(!m)redirect("/onboarding");
 await s.rpc("refresh_overdue_invoices");
 const {data:actions}=await s.from("actions").select("id,title,reason,priority,status,due_at,completed_at,clients(name)").eq("workspace_id",m.workspace_id).order("due_at",{ascending:true}).limit(100);
 const {data:invoices}=await s.from("invoices").select("id,invoice_number,amount,currency,due_date,status,client_id,clients(name),payments(amount)").eq("workspace_id",m.workspace_id).in("status",["overdue","pending","partially_paid"]).order("due_date",{ascending:true}).limit(100);
 const groups={attention:[] as any[],waiting:[] as any[],upcoming:[] as any[],completed:[] as any[]};
 (actions||[]).forEach(a=>{if(a.status==="completed")groups.completed.push(a);else if(a.status==="waiting")groups.waiting.push(a);else if(dueNow(a.due_at))groups.attention.push(a);else groups.upcoming.push(a)});
 const priorityRank={high:0,medium:1,low:2};
 groups.attention.sort((a,b)=>(priorityRank[a.priority as keyof typeof priorityRank]??9)-(priorityRank[b.priority as keyof typeof priorityRank]??9)||new Date(a.due_at||"9999-12-31").getTime()-new Date(b.due_at||"9999-12-31").getTime());
 groups.upcoming.sort((a,b)=>new Date(a.due_at||"9999-12-31").getTime()-new Date(b.due_at||"9999-12-31").getTime());
 const paymentItems=(invoices||[]).map((i:any)=>{const paid=(i.payments||[]).reduce((x:number,p:any)=>x+Number(p.amount),0);return {...i,remaining:Math.max(0,Number(i.amount)-paid)}}).filter((i:any)=>i.remaining>0);
 const AIActionHint=({clientId}:{clientId:string})=><a href={"/app/clients/"+clientId} className="mt-3 inline-flex text-xs font-semibold text-blue-700">Get AI recommendation →</a>;\n const ActionCard=({a}:{a:any})=><div className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-[#0b1736]">{a.title}</p><p className="mt-1 text-sm text-slate-500">{a.clients?.name||"Client"}</p>{a.reason&&<p className="mt-2 text-sm text-slate-600">{a.reason}</p>}</div><span className={"rounded-full px-2.5 py-1 text-[11px] font-bold uppercase "+(a.priority==="high"?"bg-red-50 text-red-700":a.priority==="medium"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-600")}>{a.priority}</span></div><div className="mt-4 flex items-center justify-between text-xs text-slate-500"><span>{a.due_at?"Due "+new Date(a.due_at).toLocaleString():"No due date"}</span><a href={"/app/actions/"+a.id} className="font-semibold text-blue-600">Review →</a></div></div>;
 const InvoiceCard=({i}:{i:any})=><div className="rounded-2xl border border-red-100 bg-white p-4"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-[#0b1736]">{i.clients?.name||"Client"} · {i.remaining.toFixed(2)} {i.currency}</p><p className="mt-1 text-sm text-slate-500">{i.invoice_number||"Invoice"} · due {i.due_date}</p><p className="mt-2 text-sm text-slate-600">{i.status==="overdue"?"Payment is overdue.":"Payment is still outstanding."}</p>{i.client_id&&<AIActionHint clientId={i.client_id}/>}</div><span className="rounded-full bg-red-50 px-2.5 py-1 text-[11px] font-bold uppercase text-red-700">{i.status}</span></div><div className="mt-4 flex justify-end"><a href={"/app/payments/"+i.id} className="text-sm font-semibold text-blue-600">Review payment →</a></div></div>;
 return <main className="px-6 py-10"><div className="mx-auto max-w-7xl"><p className="text-sm font-semibold text-blue-600">Today</p><h1 className="mt-2 text-4xl font-semibold text-[#0b1736]">Here’s what needs your attention.</h1><p className="mt-2 text-slate-500">Actionora turns pending client situations into clear next actions.</p><div className="mt-8 grid gap-3 sm:grid-cols-4"><div className="rounded-2xl border bg-white p-4"><p className="text-sm text-slate-500">Need action</p><p className="mt-1 text-3xl font-semibold">{groups.attention.length+paymentItems.filter((i:any)=>i.status==="overdue").length}</p></div><div className="rounded-2xl border bg-white p-4"><p className="text-sm text-slate-500">Waiting</p><p className="mt-1 text-3xl font-semibold">{groups.waiting.length}</p></div><div className="rounded-2xl border bg-white p-4"><p className="text-sm text-slate-500">Upcoming</p><p className="mt-1 text-3xl font-semibold">{groups.upcoming.length}</p></div><div className="rounded-2xl border bg-white p-4"><p className="text-sm text-slate-500">Completed</p><p className="mt-1 text-3xl font-semibold">{groups.completed.length}</p></div></div><section className="mt-8"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold text-[#0b1736]">Need action now</h2><a href="/app/actions/new" className="rounded-xl bg-[#0b1736] px-4 py-2.5 text-sm font-semibold text-white">+ Action</a></div><div className="mt-4 grid gap-3">{groups.attention.length?groups.attention.map(a=><ActionCard key={a.id} a={a}/>):null}{paymentItems.filter((i:any)=>i.status==="overdue").map(i=><InvoiceCard key={"invoice-"+i.id} i={i}/>)}{!groups.attention.length&&!paymentItems.some((i:any)=>i.status==="overdue")&&<div className="rounded-3xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">You’re clear for now. No action is due.</div>}</div></section><div className="mt-8 grid gap-8 lg:grid-cols-2"><section><h2 className="text-xl font-semibold text-[#0b1736]">Waiting</h2><div className="mt-4 space-y-3">{groups.waiting.slice(0,5).map(a=><ActionCard key={a.id} a={a}/>)}</div></section><section><h2 className="text-xl font-semibold text-[#0b1736]">Upcoming</h2><div className="mt-4 space-y-3">{groups.upcoming.slice(0,5).map(a=><ActionCard key={a.id} a={a}/>)}</div></section></div></div></main>;
}