"use client";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export default function AuthForm() {
  const supabase=createClient();
  const [mode,setMode]=useState<"signin"|"signup">("signup");
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [name,setName]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const r=mode==="signup"?await supabase.auth.signUp({email,password,options:{data:{full_name:name}}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);if(r.error){setMessage(r.error.message);return;}if(mode==="signup"&&!r.data.session){setMessage("Check your email to confirm your account.");return;}if(mode==="signup"){await fetch("/api/trial/claim",{method:"POST"});}window.location.href="/onboarding";}
  async function oauth(provider:"google"|"apple"){const {error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:window.location.origin+"/auth/callback"}});if(error)setMessage(error.message);}
  return <div className="mt-7"><div className="grid grid-cols-2 gap-2 rounded-xl bg-slate-100 p-1"><button onClick={()=>setMode("signup")} className="rounded-lg bg-white px-3 py-2 text-sm font-semibold">Create account</button><button onClick={()=>setMode("signin")} className="rounded-lg px-3 py-2 text-sm">Log in</button></div><div className="mt-5 grid grid-cols-2 gap-3"><button onClick={()=>oauth("google")} className="rounded-xl border px-4 py-3 text-sm font-semibold">Google</button><button onClick={()=>oauth("apple")} className="rounded-xl border px-4 py-3 text-sm font-semibold">Apple</button></div><form onSubmit={submit} className="mt-5 space-y-4">{mode==="signup"&&<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Name" className="w-full rounded-xl border p-3"/>}<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" className="w-full rounded-xl border p-3"/><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" className="w-full rounded-xl border p-3"/><button disabled={busy} className="w-full rounded-xl bg-[#0b1736] p-3.5 font-semibold text-white">{busy?"Please wait…":mode==="signup"?"Create account":"Log in"}</button></form>{message&&<p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm text-slate-600">{message}</p>}<p className="mt-5 text-xs text-slate-400">By continuing, you agree to the Terms and Privacy Policy.</p></div>;
}